(include "../include/texture_.scm")
;;(include "sprite_.scm")
(include "../include/font_.scm")
;;(include "scm-lib_.scm")
;;(include "opengl_.scm")


(define-symmetric-font "laserA" 3 7 static)
(define-symmetric-font "laserB" 3 7 static)
(define-symmetric-font "laserC" 3 7 static)
(define-symmetric-font "player_laser" 1 7 static)
(define-symmetric-font "easy" 12 8 static)
(define-symmetric-font "medium" 11 8 static)
(define-symmetric-font "hard" 8 8 static)
(define-symmetric-font "player_laser_explosion" 8 8 static)
(define-symmetric-font "invader_laser_explosion" 6 8 static)
(define-symmetric-font "invader_explosion" 13 8 static)
(define-symmetric-font "mothership" 16 7 static)
(define-symmetric-font "mothership_explosion" 21 8 static)
(define-symmetric-font "player" 13 8 static)
(define-symmetric-font "player_explosion" 16 8 static)

(define-symmetric-font "bb_fonts" 8 8 static)
 ;;(define-symmetric-font "f_operationwolf" 8 8)
;;(define-symmetric-font "f_syvalion" 16 16)
